### ISSUE TITLE
Expose `test(server | settings)` API

### ISSUE THREAD

**Issue by chrisdickinson** [npm/spife#82]
We need a control surface off of which we can hang common test functionality.

My current thought is that we could do something like:

```javascript
const createTestServer = require('@npm/spife/utils/test')
const server = createTestServer(require.resolve('../path/to/settings.js'))
```

We would hang the following APIs off of this:

- `server.request`, using [shot](https://npm.im/shot) to inject requests
- `server.intercept`, to intercept requests
- `server.setMiddleware`, to override middleware
- `server.reset`, to reset middleware to original factory settings

Ideally this would be something that a porcelain `test()` function that wraps `tap` could consume.

**Comment by nlf** [comment]
i like this. i like this very much.

**Comment by chrisdickinson** [comment]
current M.O.:

```javascript
const createTestServer = require('@npm/spife/utils/test')
const server = createTestServer(require.resolve('../lib/settings'))
const tap = require('tap')
tap.test('wow, a great test', server.isolate(async assert => {
  server.intercept(async req => {
     // attach whatever is necessary for the test to run to req here.
  })

  const {statusCode, body} = await server.request({
    method: 'GET',
    path: '/foo/bar'
  })
}))
```

```javascript
const createTestServer = require('@npm/spife/utils/test')
const server = createTestServer(require.resolve('../lib/settings'))
describe('server', () => {
  it('works', server.isolate(async () => {
  }))
})
```

**Comment by chrisdickinson** [comment]
Also thinking that these isolates hook into a new middleware lifecycle: `processTestCase`.

**Comment by nlf** [comment]
i like it, the perfect extension point for any middlewares that want to do their own cleanup in tests

**Comment by aearly** [comment]
This happened!
